name: Code Verification

on: [ push, pull_request ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Print Flutter version
        run: flutter --version
      - name: Get packages
        run: flutter pub get
      - name: Check formatting
        run: |
          # Find all .dart files in lib/ and test/, excluding .mocks.dart files.
          # Note: 'find' is a standard command on GitHub Actions Linux runners.
          FILES_TO_CHECK=$(find lib test -name '*.dart' -not -name '*.mocks.dart' | xargs echo)

          # Run dart format with the found files.
          # -o none: do not write changes back to files.
          # --set-exit-if-changed: exit with a non-zero code if any files need reformatting.
          echo "Checking format for files: $FILES_TO_CHECK"
          dart format -o none --set-exit-if-changed $FILES_TO_CHECK
          # If the above command returns a non-zero exit code, this step will fail.
      - name: Analyze the source code
        run: flutter analyze
      - name: Run tests
        run: flutter test
